#!/usr/bin/env bash
#
# Copyright (C) 2019-2024 KFERMercer <https://github.com/KFERMercer>
#

# Check for assignment of runtime variables
[ ! ${MODEL} ] || [ ! ${PLATFORM} ] || [ ! ${SAVE_PATH} ] || [ ! ${LOG_PATH} ] && echo "Incomplete Runtime Variables!" && exit 1

# Process ${MODEL}
# Assume ${MODEL} contain some link form, process & cut invalid chars.
MODEL_NAME=$(echo ${MODEL,,} \
    | grep -oE 'http[s]?://[a-zA-Z]?+[.]?[a-zA-Z]+[.][a-zA-Z]+[/][^ /]+' \
    | cut -d '/' -f4 \
    | grep -oE '[a-zA-Z0-9_-]+' \
    | head -n 1)
# If ${MODEL} not link form, cut invalid chars.
[[ ! ${MODEL_NAME} ]] && MODEL_NAME=$(echo "${MODEL,,}" | grep -oE '[a-zA-Z0-9_-]+' | head -n 1)
[[ ! ${MODEL_NAME} ]] && echo "(ERROR) Invalid Username or Link!" && exit 1

# Process $PLATFORM
PLATFORM=${PLATFORM,,}
case ${PLATFORM} in 
    chaturbate|ctb|cb)
        PLATFORM=chaturbate
    ;;
    stripchat|stc|sc|st)
        PLATFORM=stripchat
    ;;
    *)
        echo "(ERROR) Invalid Platform!" && exit 1
    ;;
esac

# Is directories writable?
[ ! -w ${SAVE_PATH} ] && echo "SAVE_PATH are unwritable!" && exit 1
[ ! -w ${LOG_PATH} ] && echo "LOG_PATH are unwritable!" && exit 1

# Flag of ffmpeg process
FFMPEG_PROCESS=$(ps -ef | grep -oE "[f]fmpeg -i.*${MODEL}.*\.m3u8*" 2>/dev/null)
# No ffmpeg process --> normal
[ ! "${FFMPEG_PROCESS}" ] && exit 0

# If Model currently online, set HTTP Status Code of m3u8 link as flag
[ -f ${LOG_PATH}/${MODEL}.online ] && M3U8_RESPONSE=$(curl $(cat ${LOG_PATH}/${PLATFORM}-${MODEL}.online) -4 -s -I -w %{http_code} -H 'user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36' 2>/dev/null | tail -n1)

# Has ffmpeg process, but m3u8 link are unavailable --> err
[ "${FFMPEG_PROCESS}" ] && [ ${M3U8_RESPONSE} -ge 400 ] && echo "(ERROR) FFMPEG process did not exit correctly!" && exit 1

exit 0
