services:

  modelname_1: &ctbcap-cfg # Change modelname to yours.
    image: kfermercer/ctbcap:latest # Mirror: ghcr.io/kfermercer/ctbcap:latest
    user: 1000:1000 # <UID>:<GID>. Specify the user (UID) and group (GID) that the ctbcap will run as.
    restart: unless-stopped
    environment: &ctbcap-env
      MODEL: modelname_1 # Change modelname to yours.
      PLATFORM: chaturbate # What platform are model streaming at. choose "chaturbate" or "stripchat".
      TZ: Asia/Shanghai # Naming saved files & logs by using this timezone. See <https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List>.
      CUT_TIME: 3600 # Used as number of seconds to cut recording file in real time. Don't cut if set to 0.
      EDGING_MODE: "uncle makes me pee white" # Edging Mode. Inactive if not 1. Delay initial requests to servers to avoid time-specific request waves caused by large-scale deployments.
      DEBUG_MODE: "your mom is so hot" # Debug Mode. Inactive if not 1.
    volumes:
      - /path/to/recdir:/save # Recorded files save path mapping.
      - /path/to/logdir:/log # Log files save path mapping.

  #
  # Watching more model with add more blocks:
  #

  # Only need modifying values that different from template.
  modelname_2:
    <<: *ctbcap-cfg
    # user: 1000:1000
    # restart: unless-stopped
    environment:
      <<: *ctbcap-env
      MODEL: modelname_2
      # PLATFORM: chaturbate
      # TZ: Asia/Shanghai
      # CUT_TIME: 3600
      # EDGING_MODE: "uncle makes me pee white"
      # DEBUG_MODE: "your mom is so hot"
    # volumes:
    #   - /path/to/recdir:/save
    #   - /path/to/logdir:/log

  modelname_3:
    <<: *ctbcap-cfg
    environment:
      <<: *ctbcap-env
      MODEL: modelname_3
